### ISSUE TITLE
CMake policy not known

### ISSUE THREAD

**Issue by kota-rr** [rapyuta-robotics/depthai_ros#11]
build error for `node_interface` from unknown cmake policy when using CMake 3.10.2.

```
Errors     << node_interface:check /home/kota/ws_depthai/logs/node_interface/build.check.000.log                                                                                                                  
CMake Error at /home/kota/ws_depthai/src/depthai_ros/node_interface/CMakeLists.txt:4 (cmake_policy):
  Policy "CMP0076" is not known to this version of CMake.
```

**Comment by kunaltyagi** [comment]
The updated CMakeLists in `depthai_ros_driver` has a mitigation implemented, but I must have missed this.

**Comment by kunaltyagi** [comment]
There's a mitigation implemented in `node_itnerface` using `if(POLICY)`. Is this error on the `master`?

**Comment by kota-rr** [comment]
> There's a mitigation implemented in `node_itnerface` using `if(POLICY)`. Is this error on the `master`?

I forgot to sync my `master` to repo, and it was fixed in the latest mater.
