### ISSUE TITLE
Create libraries for gen2 pipelines

### ISSUE THREAD

**Issue by kunaltyagi** [rapyuta-robotics/depthai_ros#31]
Could we try to do this properly? Please create a proper library that can be loaded via pluginlib for different pipelines

_Originally posted by @kunaltyagi in https://github.com/rapyuta-robotics/depthai_ros/pull/30#discussion_r677068423_

**Comment by ardiya** [comment]
Implemented by kota-san to gen2_ros branch. Closing this
