### ISSUE TITLE
libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by ExtraordinaryLiang** [rapyuta-robotics/depthai_ros#53]
--------------------------------------------------------
Profile:                     default
Extending:          [cached] /opt/ros/noetic
Workspace:                   /home/lwl/catkin_ws
--------------------------------------------------------
Build Space:        [exists] /home/lwl/catkin_ws/build
Devel Space:        [exists] /home/lwl/catkin_ws/devel
Install Space:      [unused] /home/lwl/catkin_ws/install
Log Space:          [exists] /home/lwl/catkin_ws/logs
Source Space:       [exists] /home/lwl/catkin_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------
[build] Found '6' packages in 0.0 seconds.                                                                                   
[build] Package table is up to date.                                                                                         
Starting  >>> depthai_common_msgs                                                                                            
Starting  >>> depthai_ros_msgs                                                                                               
Starting  >>> node_interface                                                                                                 
Finished  <<< node_interface                       [ 0.2 seconds ]                                                           
Finished  <<< depthai_common_msgs                  [ 0.4 seconds ]                                                           
Starting  >>> depthai_datatype_msgs                                                                                          
Finished  <<< depthai_ros_msgs                     [ 0.3 seconds ]                                                           
Finished  <<< depthai_datatype_msgs                [ 0.4 seconds ]                                                           
Starting  >>> depthai_ros_driver                                                                                             
_____________________________________________________________________________________________________________________________
Errors     << depthai_ros_driver:make /home/lwl/catkin_ws/logs/depthai_ros_driver/build.make.007.log                         
/usr/bin/ld: /home/lwl/.hunter/_Base/cae9026/64dcd41/7481f6d/Install/lib/libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make[2]: *** [depthai-core/CMakeFiles/depthai-core.dir/build.make:932：depthai-core/libdepthai-core.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2945：depthai-core/CMakeFiles/depthai-core.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
cd /home/lwl/catkin_ws/build/depthai_ros_driver; catkin build --get-env depthai_ros_driver | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

.............................................................................................................................
Failed     << depthai_ros_driver:make              [ Exited with code 2 ]                                                    
Failed    <<< depthai_ros_driver                   [ 0.6 seconds ]                                                           
Abandoned <<< depthai_ros                          [ Unrelated job failed ]                                                  
[build] Summary: 4 of 6 packages succeeded.                                                                                  
[build]   Ignored:   None.                                                                                                   
[build]   Warnings:  None.                                                                                                   
[build]   Abandoned: 1 packages were abandoned.                                                                              
[build]   Failed:    1 packages failed.                                                                                      
[build] Runtime: 1.5 seconds total.

**Comment by ardiya** [comment]
Can you try if (1)`rm ~/.hunter` (remove cache of hunter), (2) `catkin clean depthai_ros_driver` fixes the issue?

We're currently using depthai Gen2 API in the master branch. I believe your issue is just cache from old Gen1. If you'd like to use the gen1 api, you can revert back to the [v0.1-gen1 tags](https://github.com/rapyuta-robotics/depthai_ros/tree/v0.1-gen1)

**Comment by ardiya** [comment]
Another possibilities is by adding this `catkin config --cmake-args -DDEPTHAI_ENABLE_BACKWARD=OFF --`

Seems like some of depthai stuff breaks after this https://github.com/luxonis/depthai-core/pull/223

**Comment by ExtraordinaryLiang** [comment]
> 

Thanks, it works！
